---
- name: Create Docker Container
  hosts: localhost
  connection: local  
  remote_user: root
  tasks:
      - name: Install python-docker on Red Hat based distribution
        yum:
         name: python-docker
         enablerepo: extras
         state: latest
        when: ansible_os_family == 'RedHat'
      - name: Install python-docker  on Debian based distribution
        apt: 
          name: python-docker
          update_cache: yes
        when: ansible_os_family == 'Debian' 
      - name: Create Container
        docker_container:
              name: "webApp"
              image: "webApp:webapp:${BUILD_NUMBER}"
              ports:
                - "1238:8080"
              volume:
                - tomcat_data:/usr/local/tomcat
              privileged: "true"

