---
- name: Create Docker Container
  hosts: localhost
  connection: local  
  remote_user: root
  tasks: 
      - name: Create Container
        docker_container:
              name: "webapp_${BUILD_NUMBER}"
              image: "webapp:${BUILD_NUMBER}"
              ports:
                - "1238:8080"
              volume:
                - tomcat_data:/usr/local/tomcat
              privileged: "true"

