---
- name: Create Docker Container
  hosts: localhost
  connection: local  
  become_method: sudo
  become: yes
  tasks:
      - name: Install python-docker on Red Hat based distribution
        yum:
         name: python-docker
         enablerepo: extras
         state: latest
        when: ansible_os_family == 'RedHat'
      - name: Install python-docker  on Debian based distribution
        apt: 
          name: python-docker
          update_cache: yes
        when: ansible_os_family == 'Debian' 
      - name: Create Container
        docker_container:
              name: "{{ container }}"
              image: "{{ image }}"
              ports:
                - "1238:8080"
              privileged: "true"

...